//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstCafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int UrunNo { get; set; }
        public string Yemekler { get; set; }
        public string Icecekler { get; set; }
        public string Tatlilar { get; set; }
    }
}
